// flow-typed signature: ef80f60a0fb2487896f2a27492bf063f
// flow-typed version: <<STUB>>/animate.css_v^3.5.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate.css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animate.css/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animate.css/gulpfile.js' {
  declare module.exports: $Exports<'animate.css/gulpfile'>;
}
