// flow-typed signature: 7da676906a5f4a13ca747b842476d0a0
// flow-typed version: <<STUB>>/cldr-data_v^29.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cldr-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cldr-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cldr-data/Gruntfile' {
  declare module.exports: any;
}

declare module 'cldr-data/install' {
  declare module.exports: any;
}

declare module 'cldr-data/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cldr-data/Gruntfile.js' {
  declare module.exports: $Exports<'cldr-data/Gruntfile'>;
}
declare module 'cldr-data/index' {
  declare module.exports: $Exports<'cldr-data'>;
}
declare module 'cldr-data/index.js' {
  declare module.exports: $Exports<'cldr-data'>;
}
declare module 'cldr-data/install.js' {
  declare module.exports: $Exports<'cldr-data/install'>;
}
declare module 'cldr-data/test/index.js' {
  declare module.exports: $Exports<'cldr-data/test/index'>;
}
