// flow-typed signature: 554a3d9a0b299554a12042ce5136d2a1
// flow-typed version: <<STUB>>/dancedeets-common_vfile:../common/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dancedeets-common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dancedeets-common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dancedeets-common/js/dates' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/events/helpers' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/events/messages' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/events/models' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/events/people' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/events/search' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/intl' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/languages/data' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/languages/index' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/styles/icons' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/styles/index' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/tutorials/format' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/tutorials/messages' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/tutorials/models' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/tutorials/playlistConfig' {
  declare module.exports: any;
}

declare module 'dancedeets-common/js/util/sort' {
  declare module.exports: any;
}

declare module 'dancedeets-common/scripts/_youtube' {
  declare module.exports: any;
}

declare module 'dancedeets-common/scripts/battleClassifier' {
  declare module.exports: any;
}

declare module 'dancedeets-common/scripts/checkTutorials' {
  declare module.exports: any;
}

declare module 'dancedeets-common/scripts/fetchYoutubeVideos' {
  declare module.exports: any;
}

declare module 'dancedeets-common/scripts/updatePlaylists' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dancedeets-common/js/dates.js' {
  declare module.exports: $Exports<'dancedeets-common/js/dates'>;
}
declare module 'dancedeets-common/js/events/helpers.js' {
  declare module.exports: $Exports<'dancedeets-common/js/events/helpers'>;
}
declare module 'dancedeets-common/js/events/messages.js' {
  declare module.exports: $Exports<'dancedeets-common/js/events/messages'>;
}
declare module 'dancedeets-common/js/events/models.js' {
  declare module.exports: $Exports<'dancedeets-common/js/events/models'>;
}
declare module 'dancedeets-common/js/events/people.js' {
  declare module.exports: $Exports<'dancedeets-common/js/events/people'>;
}
declare module 'dancedeets-common/js/events/search.js' {
  declare module.exports: $Exports<'dancedeets-common/js/events/search'>;
}
declare module 'dancedeets-common/js/intl.js' {
  declare module.exports: $Exports<'dancedeets-common/js/intl'>;
}
declare module 'dancedeets-common/js/languages/data.js' {
  declare module.exports: $Exports<'dancedeets-common/js/languages/data'>;
}
declare module 'dancedeets-common/js/languages/index.js' {
  declare module.exports: $Exports<'dancedeets-common/js/languages/index'>;
}
declare module 'dancedeets-common/js/styles/icons.js' {
  declare module.exports: $Exports<'dancedeets-common/js/styles/icons'>;
}
declare module 'dancedeets-common/js/styles/index.js' {
  declare module.exports: $Exports<'dancedeets-common/js/styles/index'>;
}
declare module 'dancedeets-common/js/tutorials/format.js' {
  declare module.exports: $Exports<'dancedeets-common/js/tutorials/format'>;
}
declare module 'dancedeets-common/js/tutorials/messages.js' {
  declare module.exports: $Exports<'dancedeets-common/js/tutorials/messages'>;
}
declare module 'dancedeets-common/js/tutorials/models.js' {
  declare module.exports: $Exports<'dancedeets-common/js/tutorials/models'>;
}
declare module 'dancedeets-common/js/tutorials/playlistConfig.js' {
  declare module.exports: $Exports<'dancedeets-common/js/tutorials/playlistConfig'>;
}
declare module 'dancedeets-common/js/util/sort.js' {
  declare module.exports: $Exports<'dancedeets-common/js/util/sort'>;
}
declare module 'dancedeets-common/scripts/_youtube.js' {
  declare module.exports: $Exports<'dancedeets-common/scripts/_youtube'>;
}
declare module 'dancedeets-common/scripts/battleClassifier.js' {
  declare module.exports: $Exports<'dancedeets-common/scripts/battleClassifier'>;
}
declare module 'dancedeets-common/scripts/checkTutorials.js' {
  declare module.exports: $Exports<'dancedeets-common/scripts/checkTutorials'>;
}
declare module 'dancedeets-common/scripts/fetchYoutubeVideos.js' {
  declare module.exports: $Exports<'dancedeets-common/scripts/fetchYoutubeVideos'>;
}
declare module 'dancedeets-common/scripts/updatePlaylists.js' {
  declare module.exports: $Exports<'dancedeets-common/scripts/updatePlaylists'>;
}
