// flow-typed signature: e64a8c7bd65625624dad84c6941fdc21
// flow-typed version: <<STUB>>/emoji-flags_v^1.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-flags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-flags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-flags/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-flags/cli.js' {
  declare module.exports: $Exports<'emoji-flags/cli'>;
}
declare module 'emoji-flags/index' {
  declare module.exports: $Exports<'emoji-flags'>;
}
declare module 'emoji-flags/index.js' {
  declare module.exports: $Exports<'emoji-flags'>;
}
