// flow-typed signature: 076192dd5b881b20fa93d35dc04734a0
// flow-typed version: <<STUB>>/favicons_vgithub:haydenbleasel/favicons/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'favicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'favicons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'favicons/es5' {
  declare module.exports: any;
}

declare module 'favicons/gulpfile' {
  declare module.exports: any;
}

declare module 'favicons/helpers-es5' {
  declare module.exports: any;
}

declare module 'favicons/helpers' {
  declare module.exports: any;
}

declare module 'favicons/test/gulpfile' {
  declare module.exports: any;
}

declare module 'favicons/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'favicons/es5.js' {
  declare module.exports: $Exports<'favicons/es5'>;
}
declare module 'favicons/gulpfile.js' {
  declare module.exports: $Exports<'favicons/gulpfile'>;
}
declare module 'favicons/helpers-es5.js' {
  declare module.exports: $Exports<'favicons/helpers-es5'>;
}
declare module 'favicons/helpers.js' {
  declare module.exports: $Exports<'favicons/helpers'>;
}
declare module 'favicons/index' {
  declare module.exports: $Exports<'favicons'>;
}
declare module 'favicons/index.js' {
  declare module.exports: $Exports<'favicons'>;
}
declare module 'favicons/test/gulpfile.js' {
  declare module.exports: $Exports<'favicons/test/gulpfile'>;
}
declare module 'favicons/test/test.js' {
  declare module.exports: $Exports<'favicons/test/test'>;
}
