// flow-typed signature: 11deb9c70e57ffa7db7c53bb8af85d9c
// flow-typed version: <<STUB>>/font-awesome_v^4.5.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
