// flow-typed signature: 18d665c659f80d1ab834af4708b4b29f
// flow-typed version: <<STUB>>/font-awesome-svg-png_vgithub:tupadr3/Font-Awesome-SVG-PNG/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome-svg-png'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome-svg-png' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'font-awesome-svg-png/font-awesome-svg-png' {
  declare module.exports: any;
}

declare module 'font-awesome-svg-png/lib/generate' {
  declare module.exports: any;
}

declare module 'font-awesome-svg-png/lib/generateIcon' {
  declare module.exports: any;
}

declare module 'font-awesome-svg-png/lib/generateSprites' {
  declare module.exports: any;
}

declare module 'font-awesome-svg-png/lib/getFontData' {
  declare module.exports: any;
}

declare module 'font-awesome-svg-png/lib/getGlyphs' {
  declare module.exports: any;
}

declare module 'font-awesome-svg-png/lib/getIconList' {
  declare module.exports: any;
}

declare module 'font-awesome-svg-png/lib/getIconSvg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'font-awesome-svg-png/font-awesome-svg-png.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/font-awesome-svg-png'>;
}
declare module 'font-awesome-svg-png/index' {
  declare module.exports: $Exports<'font-awesome-svg-png'>;
}
declare module 'font-awesome-svg-png/index.js' {
  declare module.exports: $Exports<'font-awesome-svg-png'>;
}
declare module 'font-awesome-svg-png/lib/generate.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/lib/generate'>;
}
declare module 'font-awesome-svg-png/lib/generateIcon.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/lib/generateIcon'>;
}
declare module 'font-awesome-svg-png/lib/generateSprites.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/lib/generateSprites'>;
}
declare module 'font-awesome-svg-png/lib/getFontData.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/lib/getFontData'>;
}
declare module 'font-awesome-svg-png/lib/getGlyphs.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/lib/getGlyphs'>;
}
declare module 'font-awesome-svg-png/lib/getIconList.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/lib/getIconList'>;
}
declare module 'font-awesome-svg-png/lib/getIconSvg.js' {
  declare module.exports: $Exports<'font-awesome-svg-png/lib/getIconSvg'>;
}
