// flow-typed signature: 4b28374286846069aef9cf8c13284e92
// flow-typed version: <<STUB>>/geolib_v^2.0.21/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geolib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geolib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geolib/dist/geolib.elevation' {
  declare module.exports: any;
}

declare module 'geolib/dist/geolib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geolib/dist/geolib.elevation.js' {
  declare module.exports: $Exports<'geolib/dist/geolib.elevation'>;
}
declare module 'geolib/dist/geolib.js' {
  declare module.exports: $Exports<'geolib/dist/geolib'>;
}
