// flow-typed signature: 821626fdd9c30d4a243d3663bd7560e3
// flow-typed version: <<STUB>>/git-clone_v^0.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-clone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-clone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-clone/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-clone/index' {
  declare module.exports: $Exports<'git-clone'>;
}
declare module 'git-clone/index.js' {
  declare module.exports: $Exports<'git-clone'>;
}
declare module 'git-clone/test/test.js' {
  declare module.exports: $Exports<'git-clone/test/test'>;
}
