// flow-typed signature: 85c81b9512d213a54759e65e73f80f41
// flow-typed version: <<STUB>>/gulp-responsive-images_v0.0.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-responsive-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-responsive-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-responsive-images/lib/gm' {
  declare module.exports: any;
}

declare module 'gulp-responsive-images/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-responsive-images/lib/gm.js' {
  declare module.exports: $Exports<'gulp-responsive-images/lib/gm'>;
}
declare module 'gulp-responsive-images/lib/index.js' {
  declare module.exports: $Exports<'gulp-responsive-images/lib/index'>;
}
