// flow-typed signature: 6d94c597d7a80ebcc368635eb2541953
// flow-typed version: <<STUB>>/gulp-cache_v^0.4.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-cache/lib/TaskProxy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-cache/index' {
  declare module.exports: $Exports<'gulp-cache'>;
}
declare module 'gulp-cache/index.js' {
  declare module.exports: $Exports<'gulp-cache'>;
}
declare module 'gulp-cache/lib/TaskProxy.js' {
  declare module.exports: $Exports<'gulp-cache/lib/TaskProxy'>;
}
