// flow-typed signature: 599fa2357b726b1e3f921801dbea1a22
// flow-typed version: <<STUB>>/gulp-task-listing_v^1.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-task-listing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-task-listing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-task-listing/index' {
  declare module.exports: $Exports<'gulp-task-listing'>;
}
declare module 'gulp-task-listing/index.js' {
  declare module.exports: $Exports<'gulp-task-listing'>;
}
