// flow-typed signature: 7167ba98b4341ba6637a43f1804bd0d8
// flow-typed version: <<STUB>>/gulp-favicons_v^2.2.7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-favicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-favicons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-favicons/es5' {
  declare module.exports: any;
}

declare module 'gulp-favicons/test/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-favicons/es5.js' {
  declare module.exports: $Exports<'gulp-favicons/es5'>;
}
declare module 'gulp-favicons/index' {
  declare module.exports: $Exports<'gulp-favicons'>;
}
declare module 'gulp-favicons/index.js' {
  declare module.exports: $Exports<'gulp-favicons'>;
}
declare module 'gulp-favicons/test/gulpfile.js' {
  declare module.exports: $Exports<'gulp-favicons/test/gulpfile'>;
}
