// flow-typed signature: 9837ecb6e0b2d431bc02e5e15560597e
// flow-typed version: <<STUB>>/gutil_v^1.6.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gutil'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gutil' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gutil/lib/gutil' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/add' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/addAll' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/all' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/and' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/Assert' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/by' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/byNot' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/clone' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/concat' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/each' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/filter' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/get' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/has' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/log' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/merge' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/oneBy' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/or' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/replace2' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/requireReload' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/sort' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/string' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/unique' {
  declare module.exports: any;
}

declare module 'gutil/lib/util/walk' {
  declare module.exports: any;
}

declare module 'gutil/sample/byNot' {
  declare module.exports: any;
}

declare module 'gutil/sample/replace2' {
  declare module.exports: any;
}

declare module 'gutil/sample/sort' {
  declare module.exports: any;
}

declare module 'gutil/spec/addAllSpec' {
  declare module.exports: any;
}

declare module 'gutil/spec/addSpec' {
  declare module.exports: any;
}

declare module 'gutil/spec/allSpec' {
  declare module.exports: any;
}

declare module 'gutil/spec/byNotSpec' {
  declare module.exports: any;
}

declare module 'gutil/spec/bySpec' {
  declare module.exports: any;
}

declare module 'gutil/spec/mergeSpec' {
  declare module.exports: any;
}

declare module 'gutil/spec/replace2Spec' {
  declare module.exports: any;
}

declare module 'gutil/spec/sortSpec' {
  declare module.exports: any;
}

declare module 'gutil/spec/uniqueSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gutil/lib/gutil.js' {
  declare module.exports: $Exports<'gutil/lib/gutil'>;
}
declare module 'gutil/lib/util/add.js' {
  declare module.exports: $Exports<'gutil/lib/util/add'>;
}
declare module 'gutil/lib/util/addAll.js' {
  declare module.exports: $Exports<'gutil/lib/util/addAll'>;
}
declare module 'gutil/lib/util/all.js' {
  declare module.exports: $Exports<'gutil/lib/util/all'>;
}
declare module 'gutil/lib/util/and.js' {
  declare module.exports: $Exports<'gutil/lib/util/and'>;
}
declare module 'gutil/lib/util/Assert.js' {
  declare module.exports: $Exports<'gutil/lib/util/Assert'>;
}
declare module 'gutil/lib/util/by.js' {
  declare module.exports: $Exports<'gutil/lib/util/by'>;
}
declare module 'gutil/lib/util/byNot.js' {
  declare module.exports: $Exports<'gutil/lib/util/byNot'>;
}
declare module 'gutil/lib/util/clone.js' {
  declare module.exports: $Exports<'gutil/lib/util/clone'>;
}
declare module 'gutil/lib/util/concat.js' {
  declare module.exports: $Exports<'gutil/lib/util/concat'>;
}
declare module 'gutil/lib/util/each.js' {
  declare module.exports: $Exports<'gutil/lib/util/each'>;
}
declare module 'gutil/lib/util/filter.js' {
  declare module.exports: $Exports<'gutil/lib/util/filter'>;
}
declare module 'gutil/lib/util/get.js' {
  declare module.exports: $Exports<'gutil/lib/util/get'>;
}
declare module 'gutil/lib/util/has.js' {
  declare module.exports: $Exports<'gutil/lib/util/has'>;
}
declare module 'gutil/lib/util/log.js' {
  declare module.exports: $Exports<'gutil/lib/util/log'>;
}
declare module 'gutil/lib/util/merge.js' {
  declare module.exports: $Exports<'gutil/lib/util/merge'>;
}
declare module 'gutil/lib/util/oneBy.js' {
  declare module.exports: $Exports<'gutil/lib/util/oneBy'>;
}
declare module 'gutil/lib/util/or.js' {
  declare module.exports: $Exports<'gutil/lib/util/or'>;
}
declare module 'gutil/lib/util/replace2.js' {
  declare module.exports: $Exports<'gutil/lib/util/replace2'>;
}
declare module 'gutil/lib/util/requireReload.js' {
  declare module.exports: $Exports<'gutil/lib/util/requireReload'>;
}
declare module 'gutil/lib/util/sort.js' {
  declare module.exports: $Exports<'gutil/lib/util/sort'>;
}
declare module 'gutil/lib/util/string.js' {
  declare module.exports: $Exports<'gutil/lib/util/string'>;
}
declare module 'gutil/lib/util/unique.js' {
  declare module.exports: $Exports<'gutil/lib/util/unique'>;
}
declare module 'gutil/lib/util/walk.js' {
  declare module.exports: $Exports<'gutil/lib/util/walk'>;
}
declare module 'gutil/sample/byNot.js' {
  declare module.exports: $Exports<'gutil/sample/byNot'>;
}
declare module 'gutil/sample/replace2.js' {
  declare module.exports: $Exports<'gutil/sample/replace2'>;
}
declare module 'gutil/sample/sort.js' {
  declare module.exports: $Exports<'gutil/sample/sort'>;
}
declare module 'gutil/spec/addAllSpec.js' {
  declare module.exports: $Exports<'gutil/spec/addAllSpec'>;
}
declare module 'gutil/spec/addSpec.js' {
  declare module.exports: $Exports<'gutil/spec/addSpec'>;
}
declare module 'gutil/spec/allSpec.js' {
  declare module.exports: $Exports<'gutil/spec/allSpec'>;
}
declare module 'gutil/spec/byNotSpec.js' {
  declare module.exports: $Exports<'gutil/spec/byNotSpec'>;
}
declare module 'gutil/spec/bySpec.js' {
  declare module.exports: $Exports<'gutil/spec/bySpec'>;
}
declare module 'gutil/spec/mergeSpec.js' {
  declare module.exports: $Exports<'gutil/spec/mergeSpec'>;
}
declare module 'gutil/spec/replace2Spec.js' {
  declare module.exports: $Exports<'gutil/spec/replace2Spec'>;
}
declare module 'gutil/spec/sortSpec.js' {
  declare module.exports: $Exports<'gutil/spec/sortSpec'>;
}
declare module 'gutil/spec/uniqueSpec.js' {
  declare module.exports: $Exports<'gutil/spec/uniqueSpec'>;
}
