// flow-typed signature: e04ca3dad5c0ae523288dec09bc51fff
// flow-typed version: <<STUB>>/jquery-backstretch_v^2.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-backstretch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-backstretch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-backstretch/Gruntfile' {
  declare module.exports: any;
}

declare module 'jquery-backstretch/jquery.backstretch' {
  declare module.exports: any;
}

declare module 'jquery-backstretch/jquery.backstretch.min' {
  declare module.exports: any;
}

declare module 'jquery-backstretch/libs/jquery-loader' {
  declare module.exports: any;
}

declare module 'jquery-backstretch/libs/jquery/jquery' {
  declare module.exports: any;
}

declare module 'jquery-backstretch/libs/qunit/qunit' {
  declare module.exports: any;
}

declare module 'jquery-backstretch/src/jquery.backstretch' {
  declare module.exports: any;
}

declare module 'jquery-backstretch/test/backstretch_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-backstretch/Gruntfile.js' {
  declare module.exports: $Exports<'jquery-backstretch/Gruntfile'>;
}
declare module 'jquery-backstretch/jquery.backstretch.js' {
  declare module.exports: $Exports<'jquery-backstretch/jquery.backstretch'>;
}
declare module 'jquery-backstretch/jquery.backstretch.min.js' {
  declare module.exports: $Exports<'jquery-backstretch/jquery.backstretch.min'>;
}
declare module 'jquery-backstretch/libs/jquery-loader.js' {
  declare module.exports: $Exports<'jquery-backstretch/libs/jquery-loader'>;
}
declare module 'jquery-backstretch/libs/jquery/jquery.js' {
  declare module.exports: $Exports<'jquery-backstretch/libs/jquery/jquery'>;
}
declare module 'jquery-backstretch/libs/qunit/qunit.js' {
  declare module.exports: $Exports<'jquery-backstretch/libs/qunit/qunit'>;
}
declare module 'jquery-backstretch/src/jquery.backstretch.js' {
  declare module.exports: $Exports<'jquery-backstretch/src/jquery.backstretch'>;
}
declare module 'jquery-backstretch/test/backstretch_test.js' {
  declare module.exports: $Exports<'jquery-backstretch/test/backstretch_test'>;
}
