// flow-typed signature: 88318c93024eeeda589d9d3da449d79c
// flow-typed version: <<STUB>>/jquery.smartbanner_v^0.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery.smartbanner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery.smartbanner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery.smartbanner/jquery.smartbanner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery.smartbanner/jquery.smartbanner.js' {
  declare module.exports: $Exports<'jquery.smartbanner/jquery.smartbanner'>;
}
