// flow-typed signature: e07927aec9b2fa97557aaaa59e11cd77
// flow-typed version: <<STUB>>/parse-json_v^2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-json/vendor/parse' {
  declare module.exports: any;
}

declare module 'parse-json/vendor/unicode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-json/index' {
  declare module.exports: $Exports<'parse-json'>;
}
declare module 'parse-json/index.js' {
  declare module.exports: $Exports<'parse-json'>;
}
declare module 'parse-json/vendor/parse.js' {
  declare module.exports: $Exports<'parse-json/vendor/parse'>;
}
declare module 'parse-json/vendor/unicode.js' {
  declare module.exports: $Exports<'parse-json/vendor/unicode'>;
}
