// flow-typed signature: 0b445fdf6ea499b8627d9777c1cfc47b
// flow-typed version: <<STUB>>/pleeease_v^4.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pleeease'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pleeease' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pleeease/Gulpfile' {
  declare module.exports: any;
}

declare module 'pleeease/lib/browsers' {
  declare module.exports: any;
}

declare module 'pleeease/lib/options' {
  declare module.exports: any;
}

declare module 'pleeease/lib/pleeease' {
  declare module.exports: any;
}

declare module 'pleeease/lib/preprocessor' {
  declare module.exports: any;
}

declare module 'pleeease/lib/processors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pleeease/Gulpfile.js' {
  declare module.exports: $Exports<'pleeease/Gulpfile'>;
}
declare module 'pleeease/lib/browsers.js' {
  declare module.exports: $Exports<'pleeease/lib/browsers'>;
}
declare module 'pleeease/lib/options.js' {
  declare module.exports: $Exports<'pleeease/lib/options'>;
}
declare module 'pleeease/lib/pleeease.js' {
  declare module.exports: $Exports<'pleeease/lib/pleeease'>;
}
declare module 'pleeease/lib/preprocessor.js' {
  declare module.exports: $Exports<'pleeease/lib/preprocessor'>;
}
declare module 'pleeease/lib/processors.js' {
  declare module.exports: $Exports<'pleeease/lib/processors'>;
}
