// flow-typed signature: 7f26ef268c8d1509105f6ea213d2955f
// flow-typed version: <<STUB>>/psi_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'psi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'psi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'psi/cli' {
  declare module.exports: any;
}

declare module 'psi/lib/formats/cli' {
  declare module.exports: any;
}

declare module 'psi/lib/formats/json' {
  declare module.exports: any;
}

declare module 'psi/lib/formats/tap' {
  declare module.exports: any;
}

declare module 'psi/lib/output' {
  declare module.exports: any;
}

declare module 'psi/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'psi/cli.js' {
  declare module.exports: $Exports<'psi/cli'>;
}
declare module 'psi/index' {
  declare module.exports: $Exports<'psi'>;
}
declare module 'psi/index.js' {
  declare module.exports: $Exports<'psi'>;
}
declare module 'psi/lib/formats/cli.js' {
  declare module.exports: $Exports<'psi/lib/formats/cli'>;
}
declare module 'psi/lib/formats/json.js' {
  declare module.exports: $Exports<'psi/lib/formats/json'>;
}
declare module 'psi/lib/formats/tap.js' {
  declare module.exports: $Exports<'psi/lib/formats/tap'>;
}
declare module 'psi/lib/output.js' {
  declare module.exports: $Exports<'psi/lib/output'>;
}
declare module 'psi/lib/utils.js' {
  declare module.exports: $Exports<'psi/lib/utils'>;
}
