// flow-typed signature: 8895cefedfc44fba3cb96da013ea0ab8
// flow-typed version: <<STUB>>/react-native-segmented-android_vgithub:mikelambert/react-native-segmented-android/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-segmented-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-segmented-android' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-segmented-android/AndroidSegmented.android' {
  declare module.exports: any;
}

declare module 'react-native-segmented-android/AndroidSegmented.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-segmented-android/AndroidSegmented.android.js' {
  declare module.exports: $Exports<'react-native-segmented-android/AndroidSegmented.android'>;
}
declare module 'react-native-segmented-android/AndroidSegmented.ios.js' {
  declare module.exports: $Exports<'react-native-segmented-android/AndroidSegmented.ios'>;
}
