// flow-typed signature: 54c3d0f00e62249f76cbb97a0c441b4a
// flow-typed version: <<STUB>>/react-native-maps_v^0.15.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-maps/lib/components/AnimatedRegion' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/decorateMapComponent' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapCallout' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapCircle' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapMarker' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapPolygon' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapPolyline' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapUrlTile' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapView' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/ProviderConstants' {
  declare module.exports: any;
}

declare module 'react-native-maps/rn-cli.config' {
  declare module.exports: any;
}

declare module 'react-native-maps/scripts/update-version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-maps/index' {
  declare module.exports: $Exports<'react-native-maps'>;
}
declare module 'react-native-maps/index.js' {
  declare module.exports: $Exports<'react-native-maps'>;
}
declare module 'react-native-maps/lib/components/AnimatedRegion.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/AnimatedRegion'>;
}
declare module 'react-native-maps/lib/components/decorateMapComponent.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/decorateMapComponent'>;
}
declare module 'react-native-maps/lib/components/MapCallout.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapCallout'>;
}
declare module 'react-native-maps/lib/components/MapCircle.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapCircle'>;
}
declare module 'react-native-maps/lib/components/MapMarker.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapMarker'>;
}
declare module 'react-native-maps/lib/components/MapPolygon.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapPolygon'>;
}
declare module 'react-native-maps/lib/components/MapPolyline.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapPolyline'>;
}
declare module 'react-native-maps/lib/components/MapUrlTile.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapUrlTile'>;
}
declare module 'react-native-maps/lib/components/MapView.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapView'>;
}
declare module 'react-native-maps/lib/components/ProviderConstants.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/ProviderConstants'>;
}
declare module 'react-native-maps/rn-cli.config.js' {
  declare module.exports: $Exports<'react-native-maps/rn-cli.config'>;
}
declare module 'react-native-maps/scripts/update-version.js' {
  declare module.exports: $Exports<'react-native-maps/scripts/update-version'>;
}
