// flow-typed signature: 262610179b31a49785e7ca57967017b5
// flow-typed version: <<STUB>>/react-native-firebase3_v0.1.5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-firebase3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-firebase3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-firebase3/Analytics' {
  declare module.exports: any;
}

declare module 'react-native-firebase3/RemoteConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-firebase3/Analytics.js' {
  declare module.exports: $Exports<'react-native-firebase3/Analytics'>;
}
declare module 'react-native-firebase3/index' {
  declare module.exports: $Exports<'react-native-firebase3'>;
}
declare module 'react-native-firebase3/index.js' {
  declare module.exports: $Exports<'react-native-firebase3'>;
}
declare module 'react-native-firebase3/RemoteConfig.js' {
  declare module.exports: $Exports<'react-native-firebase3/RemoteConfig'>;
}
