// flow-typed signature: 3f436661b16fea8ee477ccafad946c48
// flow-typed version: <<STUB>>/react-native-permissions_vgithub:mikelambert/react-native-permissions/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-permissions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-permissions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-permissions/Example/Example' {
  declare module.exports: any;
}

declare module 'react-native-permissions/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-permissions/ReactNativePermissions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-permissions/Example/Example.js' {
  declare module.exports: $Exports<'react-native-permissions/Example/Example'>;
}
declare module 'react-native-permissions/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-permissions/Example/index.android'>;
}
declare module 'react-native-permissions/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/Example/index.ios'>;
}
declare module 'react-native-permissions/ReactNativePermissions.js' {
  declare module.exports: $Exports<'react-native-permissions/ReactNativePermissions'>;
}
