// flow-typed signature: 9089e84b0b2e20a3b766f7d125145abf
// flow-typed version: <<STUB>>/react-native-calendar-events_vgithub:mikelambert/react-native-calendar-events/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-calendar-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-calendar-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-calendar-events/index.android' {
  declare module.exports: any;
}

declare module 'react-native-calendar-events/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-calendar-events/index.android.js' {
  declare module.exports: $Exports<'react-native-calendar-events/index.android'>;
}
declare module 'react-native-calendar-events/index.ios.js' {
  declare module.exports: $Exports<'react-native-calendar-events/index.ios'>;
}
