// flow-typed signature: ff3a1d3927ccd0aeab203529ad0426ef
// flow-typed version: <<STUB>>/react-native-carousel_v^0.10.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-carousel/Carousel' {
  declare module.exports: any;
}

declare module 'react-native-carousel/CarouselPager.android' {
  declare module.exports: any;
}

declare module 'react-native-carousel/CarouselPager.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-carousel/Carousel.js' {
  declare module.exports: $Exports<'react-native-carousel/Carousel'>;
}
declare module 'react-native-carousel/CarouselPager.android.js' {
  declare module.exports: $Exports<'react-native-carousel/CarouselPager.android'>;
}
declare module 'react-native-carousel/CarouselPager.ios.js' {
  declare module.exports: $Exports<'react-native-carousel/CarouselPager.ios'>;
}
