// flow-typed signature: 8dde88d2ae7a79f7d8b36305a73add61
// flow-typed version: <<STUB>>/react-native-geocoder_v^0.4.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-geocoder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-geocoder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-geocoder/js/geocoder' {
  declare module.exports: any;
}

declare module 'react-native-geocoder/js/googleApi' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-geocoder/index' {
  declare module.exports: $Exports<'react-native-geocoder'>;
}
declare module 'react-native-geocoder/index.js' {
  declare module.exports: $Exports<'react-native-geocoder'>;
}
declare module 'react-native-geocoder/js/geocoder.js' {
  declare module.exports: $Exports<'react-native-geocoder/js/geocoder'>;
}
declare module 'react-native-geocoder/js/googleApi.js' {
  declare module.exports: $Exports<'react-native-geocoder/js/googleApi'>;
}
