// flow-typed signature: dc17320387b01a97ab170d212ec2c6ef
// flow-typed version: <<STUB>>/react-native-fabric-crashlytics_v^0.1.5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fabric-crashlytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fabric-crashlytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-fabric-crashlytics/index' {
  declare module.exports: $Exports<'react-native-fabric-crashlytics'>;
}
declare module 'react-native-fabric-crashlytics/index.js' {
  declare module.exports: $Exports<'react-native-fabric-crashlytics'>;
}
