// flow-typed signature: e440524dd3296773bafd012c1d5b6182
// flow-typed version: <<STUB>>/react-native-send-intent_v^1.0.13/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-send-intent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-send-intent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-send-intent/index' {
  declare module.exports: $Exports<'react-native-send-intent'>;
}
declare module 'react-native-send-intent/index.js' {
  declare module.exports: $Exports<'react-native-send-intent'>;
}
