// flow-typed signature: 1b53882d3c5a29f169b2daa0f1c9d754
// flow-typed version: <<STUB>>/react-native-gifted-form_v0.0.13/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-gifted-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-gifted-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-gifted-form/GiftedForm' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/GiftedFormManager' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/mixins/ContainerMixin' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/mixins/WidgetMixin' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/DatePickerIOSWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/ErrorsWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/GooglePlacesWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/GroupWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/HiddenWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/LoadingWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/ModalWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/NoticeWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/OptionWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/RowWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/SelectCountryWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/SelectWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/SeparatorWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/SubmitWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/SwitchWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/TextAreaWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/TextInputWidget' {
  declare module.exports: any;
}

declare module 'react-native-gifted-form/widgets/ValidationErrorWidget' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-gifted-form/GiftedForm.js' {
  declare module.exports: $Exports<'react-native-gifted-form/GiftedForm'>;
}
declare module 'react-native-gifted-form/GiftedFormManager.js' {
  declare module.exports: $Exports<'react-native-gifted-form/GiftedFormManager'>;
}
declare module 'react-native-gifted-form/mixins/ContainerMixin.js' {
  declare module.exports: $Exports<'react-native-gifted-form/mixins/ContainerMixin'>;
}
declare module 'react-native-gifted-form/mixins/WidgetMixin.js' {
  declare module.exports: $Exports<'react-native-gifted-form/mixins/WidgetMixin'>;
}
declare module 'react-native-gifted-form/widgets/DatePickerIOSWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/DatePickerIOSWidget'>;
}
declare module 'react-native-gifted-form/widgets/ErrorsWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/ErrorsWidget'>;
}
declare module 'react-native-gifted-form/widgets/GooglePlacesWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/GooglePlacesWidget'>;
}
declare module 'react-native-gifted-form/widgets/GroupWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/GroupWidget'>;
}
declare module 'react-native-gifted-form/widgets/HiddenWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/HiddenWidget'>;
}
declare module 'react-native-gifted-form/widgets/LoadingWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/LoadingWidget'>;
}
declare module 'react-native-gifted-form/widgets/ModalWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/ModalWidget'>;
}
declare module 'react-native-gifted-form/widgets/NoticeWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/NoticeWidget'>;
}
declare module 'react-native-gifted-form/widgets/OptionWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/OptionWidget'>;
}
declare module 'react-native-gifted-form/widgets/RowWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/RowWidget'>;
}
declare module 'react-native-gifted-form/widgets/SelectCountryWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/SelectCountryWidget'>;
}
declare module 'react-native-gifted-form/widgets/SelectWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/SelectWidget'>;
}
declare module 'react-native-gifted-form/widgets/SeparatorWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/SeparatorWidget'>;
}
declare module 'react-native-gifted-form/widgets/SubmitWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/SubmitWidget'>;
}
declare module 'react-native-gifted-form/widgets/SwitchWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/SwitchWidget'>;
}
declare module 'react-native-gifted-form/widgets/TextAreaWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/TextAreaWidget'>;
}
declare module 'react-native-gifted-form/widgets/TextInputWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/TextInputWidget'>;
}
declare module 'react-native-gifted-form/widgets/ValidationErrorWidget.js' {
  declare module.exports: $Exports<'react-native-gifted-form/widgets/ValidationErrorWidget'>;
}
