// flow-typed signature: 82ea0ec7b952d7134a2769382a1e0e54
// flow-typed version: <<STUB>>/react-native-google-api-availability_v^0.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-google-api-availability'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-google-api-availability' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-google-api-availability/index.android' {
  declare module.exports: any;
}

declare module 'react-native-google-api-availability/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-google-api-availability/index.android.js' {
  declare module.exports: $Exports<'react-native-google-api-availability/index.android'>;
}
declare module 'react-native-google-api-availability/index.ios.js' {
  declare module.exports: $Exports<'react-native-google-api-availability/index.ios'>;
}
