// flow-typed signature: 33eb3b3e167dcfa8cdf34b9d9e518cca
// flow-typed version: <<STUB>>/react-devtools_v^2.3.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-devtools/app' {
  declare module.exports: any;
}

declare module 'react-devtools/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-devtools/app.js' {
  declare module.exports: $Exports<'react-devtools/app'>;
}
declare module 'react-devtools/bin.js' {
  declare module.exports: $Exports<'react-devtools/bin'>;
}
declare module 'react-devtools/index' {
  declare module.exports: $Exports<'react-devtools'>;
}
declare module 'react-devtools/index.js' {
  declare module.exports: $Exports<'react-devtools'>;
}
