// flow-typed signature: 25a611a7ca9ac0f834850c940334646e
// flow-typed version: <<STUB>>/react-native-native-env_v0.0.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-native-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-native-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-native-env/index' {
  declare module.exports: $Exports<'react-native-native-env'>;
}
declare module 'react-native-native-env/index.js' {
  declare module.exports: $Exports<'react-native-native-env'>;
}
