// flow-typed signature: a8364b8a03d05de987e3a12a99b1dcc5
// flow-typed version: <<STUB>>/react-slick_v^0.14.5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slick/__tests__/arrows' {
  declare module.exports: any;
}

declare module 'react-slick/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-slick/__tests__/sample' {
  declare module.exports: any;
}

declare module 'react-slick/dist/react-slick' {
  declare module.exports: any;
}

declare module 'react-slick/dist/react-slick.min' {
  declare module.exports: any;
}

declare module 'react-slick/docs/demos' {
  declare module.exports: any;
}

declare module 'react-slick/docs/docs' {
  declare module.exports: any;
}

declare module 'react-slick/docs/index' {
  declare module.exports: any;
}

declare module 'react-slick/docs/routes' {
  declare module.exports: any;
}

declare module 'react-slick/examples/AdaptiveHeight' {
  declare module.exports: any;
}

declare module 'react-slick/examples/AutoPlay' {
  declare module.exports: any;
}

declare module 'react-slick/examples/CenterMode' {
  declare module.exports: any;
}

declare module 'react-slick/examples/config' {
  declare module.exports: any;
}

declare module 'react-slick/examples/CustomArrows' {
  declare module.exports: any;
}

declare module 'react-slick/examples/CustomPaging' {
  declare module.exports: any;
}

declare module 'react-slick/examples/CustomSlides' {
  declare module.exports: any;
}

declare module 'react-slick/examples/DynamicSlides' {
  declare module.exports: any;
}

declare module 'react-slick/examples/Fade' {
  declare module.exports: any;
}

declare module 'react-slick/examples/FocusOnSelect' {
  declare module.exports: any;
}

declare module 'react-slick/examples/LazyLoad' {
  declare module.exports: any;
}

declare module 'react-slick/examples/MultipleItems' {
  declare module.exports: any;
}

declare module 'react-slick/examples/PauseOnHover' {
  declare module.exports: any;
}

declare module 'react-slick/examples/PreviousNextMethods' {
  declare module.exports: any;
}

declare module 'react-slick/examples/Responsive' {
  declare module.exports: any;
}

declare module 'react-slick/examples/Rtl' {
  declare module.exports: any;
}

declare module 'react-slick/examples/SimpleSlider' {
  declare module.exports: any;
}

declare module 'react-slick/examples/SlickGoTo' {
  declare module.exports: any;
}

declare module 'react-slick/examples/SlideChangeHooks' {
  declare module.exports: any;
}

declare module 'react-slick/examples/SwipeToSlide' {
  declare module.exports: any;
}

declare module 'react-slick/examples/UnevenSetsFinite' {
  declare module.exports: any;
}

declare module 'react-slick/examples/UnevenSetsInfinite' {
  declare module.exports: any;
}

declare module 'react-slick/examples/VariableWidth' {
  declare module.exports: any;
}

declare module 'react-slick/examples/VerticalMode' {
  declare module.exports: any;
}

declare module 'react-slick/examples/VerticalSwipeToSlide' {
  declare module.exports: any;
}

declare module 'react-slick/lib/arrows' {
  declare module.exports: any;
}

declare module 'react-slick/lib/default-props' {
  declare module.exports: any;
}

declare module 'react-slick/lib/dots' {
  declare module.exports: any;
}

declare module 'react-slick/lib/index' {
  declare module.exports: any;
}

declare module 'react-slick/lib/initial-state' {
  declare module.exports: any;
}

declare module 'react-slick/lib/inner-slider' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/event-handlers' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/helpers' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/trackHelper' {
  declare module.exports: any;
}

declare module 'react-slick/lib/slider' {
  declare module.exports: any;
}

declare module 'react-slick/lib/track' {
  declare module.exports: any;
}

declare module 'react-slick/src/arrows' {
  declare module.exports: any;
}

declare module 'react-slick/src/default-props' {
  declare module.exports: any;
}

declare module 'react-slick/src/dots' {
  declare module.exports: any;
}

declare module 'react-slick/src/index' {
  declare module.exports: any;
}

declare module 'react-slick/src/initial-state' {
  declare module.exports: any;
}

declare module 'react-slick/src/inner-slider' {
  declare module.exports: any;
}

declare module 'react-slick/src/mixins/event-handlers' {
  declare module.exports: any;
}

declare module 'react-slick/src/mixins/helpers' {
  declare module.exports: any;
}

declare module 'react-slick/src/mixins/trackHelper' {
  declare module.exports: any;
}

declare module 'react-slick/src/slider' {
  declare module.exports: any;
}

declare module 'react-slick/src/track' {
  declare module.exports: any;
}

declare module 'react-slick/test-setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slick/__tests__/arrows.js' {
  declare module.exports: $Exports<'react-slick/__tests__/arrows'>;
}
declare module 'react-slick/__tests__/index.js' {
  declare module.exports: $Exports<'react-slick/__tests__/index'>;
}
declare module 'react-slick/__tests__/sample.js' {
  declare module.exports: $Exports<'react-slick/__tests__/sample'>;
}
declare module 'react-slick/dist/react-slick.js' {
  declare module.exports: $Exports<'react-slick/dist/react-slick'>;
}
declare module 'react-slick/dist/react-slick.min.js' {
  declare module.exports: $Exports<'react-slick/dist/react-slick.min'>;
}
declare module 'react-slick/docs/demos.jsx' {
  declare module.exports: $Exports<'react-slick/docs/demos'>;
}
declare module 'react-slick/docs/docs.jsx' {
  declare module.exports: $Exports<'react-slick/docs/docs'>;
}
declare module 'react-slick/docs/index.jsx' {
  declare module.exports: $Exports<'react-slick/docs/index'>;
}
declare module 'react-slick/docs/routes.jsx' {
  declare module.exports: $Exports<'react-slick/docs/routes'>;
}
declare module 'react-slick/examples/AdaptiveHeight.js' {
  declare module.exports: $Exports<'react-slick/examples/AdaptiveHeight'>;
}
declare module 'react-slick/examples/AutoPlay.js' {
  declare module.exports: $Exports<'react-slick/examples/AutoPlay'>;
}
declare module 'react-slick/examples/CenterMode.js' {
  declare module.exports: $Exports<'react-slick/examples/CenterMode'>;
}
declare module 'react-slick/examples/config.js' {
  declare module.exports: $Exports<'react-slick/examples/config'>;
}
declare module 'react-slick/examples/CustomArrows.js' {
  declare module.exports: $Exports<'react-slick/examples/CustomArrows'>;
}
declare module 'react-slick/examples/CustomPaging.js' {
  declare module.exports: $Exports<'react-slick/examples/CustomPaging'>;
}
declare module 'react-slick/examples/CustomSlides.js' {
  declare module.exports: $Exports<'react-slick/examples/CustomSlides'>;
}
declare module 'react-slick/examples/DynamicSlides.js' {
  declare module.exports: $Exports<'react-slick/examples/DynamicSlides'>;
}
declare module 'react-slick/examples/Fade.js' {
  declare module.exports: $Exports<'react-slick/examples/Fade'>;
}
declare module 'react-slick/examples/FocusOnSelect.js' {
  declare module.exports: $Exports<'react-slick/examples/FocusOnSelect'>;
}
declare module 'react-slick/examples/LazyLoad.js' {
  declare module.exports: $Exports<'react-slick/examples/LazyLoad'>;
}
declare module 'react-slick/examples/MultipleItems.js' {
  declare module.exports: $Exports<'react-slick/examples/MultipleItems'>;
}
declare module 'react-slick/examples/PauseOnHover.js' {
  declare module.exports: $Exports<'react-slick/examples/PauseOnHover'>;
}
declare module 'react-slick/examples/PreviousNextMethods.js' {
  declare module.exports: $Exports<'react-slick/examples/PreviousNextMethods'>;
}
declare module 'react-slick/examples/Responsive.js' {
  declare module.exports: $Exports<'react-slick/examples/Responsive'>;
}
declare module 'react-slick/examples/Rtl.js' {
  declare module.exports: $Exports<'react-slick/examples/Rtl'>;
}
declare module 'react-slick/examples/SimpleSlider.js' {
  declare module.exports: $Exports<'react-slick/examples/SimpleSlider'>;
}
declare module 'react-slick/examples/SlickGoTo.js' {
  declare module.exports: $Exports<'react-slick/examples/SlickGoTo'>;
}
declare module 'react-slick/examples/SlideChangeHooks.js' {
  declare module.exports: $Exports<'react-slick/examples/SlideChangeHooks'>;
}
declare module 'react-slick/examples/SwipeToSlide.js' {
  declare module.exports: $Exports<'react-slick/examples/SwipeToSlide'>;
}
declare module 'react-slick/examples/UnevenSetsFinite.js' {
  declare module.exports: $Exports<'react-slick/examples/UnevenSetsFinite'>;
}
declare module 'react-slick/examples/UnevenSetsInfinite.js' {
  declare module.exports: $Exports<'react-slick/examples/UnevenSetsInfinite'>;
}
declare module 'react-slick/examples/VariableWidth.js' {
  declare module.exports: $Exports<'react-slick/examples/VariableWidth'>;
}
declare module 'react-slick/examples/VerticalMode.js' {
  declare module.exports: $Exports<'react-slick/examples/VerticalMode'>;
}
declare module 'react-slick/examples/VerticalSwipeToSlide.js' {
  declare module.exports: $Exports<'react-slick/examples/VerticalSwipeToSlide'>;
}
declare module 'react-slick/lib/arrows.js' {
  declare module.exports: $Exports<'react-slick/lib/arrows'>;
}
declare module 'react-slick/lib/default-props.js' {
  declare module.exports: $Exports<'react-slick/lib/default-props'>;
}
declare module 'react-slick/lib/dots.js' {
  declare module.exports: $Exports<'react-slick/lib/dots'>;
}
declare module 'react-slick/lib/index.js' {
  declare module.exports: $Exports<'react-slick/lib/index'>;
}
declare module 'react-slick/lib/initial-state.js' {
  declare module.exports: $Exports<'react-slick/lib/initial-state'>;
}
declare module 'react-slick/lib/inner-slider.js' {
  declare module.exports: $Exports<'react-slick/lib/inner-slider'>;
}
declare module 'react-slick/lib/mixins/event-handlers.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/event-handlers'>;
}
declare module 'react-slick/lib/mixins/helpers.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/helpers'>;
}
declare module 'react-slick/lib/mixins/trackHelper.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/trackHelper'>;
}
declare module 'react-slick/lib/slider.js' {
  declare module.exports: $Exports<'react-slick/lib/slider'>;
}
declare module 'react-slick/lib/track.js' {
  declare module.exports: $Exports<'react-slick/lib/track'>;
}
declare module 'react-slick/src/arrows.js' {
  declare module.exports: $Exports<'react-slick/src/arrows'>;
}
declare module 'react-slick/src/default-props.js' {
  declare module.exports: $Exports<'react-slick/src/default-props'>;
}
declare module 'react-slick/src/dots.js' {
  declare module.exports: $Exports<'react-slick/src/dots'>;
}
declare module 'react-slick/src/index.js' {
  declare module.exports: $Exports<'react-slick/src/index'>;
}
declare module 'react-slick/src/initial-state.js' {
  declare module.exports: $Exports<'react-slick/src/initial-state'>;
}
declare module 'react-slick/src/inner-slider.js' {
  declare module.exports: $Exports<'react-slick/src/inner-slider'>;
}
declare module 'react-slick/src/mixins/event-handlers.js' {
  declare module.exports: $Exports<'react-slick/src/mixins/event-handlers'>;
}
declare module 'react-slick/src/mixins/helpers.js' {
  declare module.exports: $Exports<'react-slick/src/mixins/helpers'>;
}
declare module 'react-slick/src/mixins/trackHelper.js' {
  declare module.exports: $Exports<'react-slick/src/mixins/trackHelper'>;
}
declare module 'react-slick/src/slider.js' {
  declare module.exports: $Exports<'react-slick/src/slider'>;
}
declare module 'react-slick/src/track.js' {
  declare module.exports: $Exports<'react-slick/src/track'>;
}
declare module 'react-slick/test-setup.js' {
  declare module.exports: $Exports<'react-slick/test-setup'>;
}
