// flow-typed signature: eb9e8e3ff68f892ceb17fcbde2488af5
// flow-typed version: <<STUB>>/react-native-trackjs_v^0.1.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-trackjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-trackjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-trackjs/index' {
  declare module.exports: $Exports<'react-native-trackjs'>;
}
declare module 'react-native-trackjs/index.js' {
  declare module.exports: $Exports<'react-native-trackjs'>;
}
