// flow-typed signature: a8acb5d495545a77ca5585bcbf9ac3d4
// flow-typed version: <<STUB>>/react-native-firestack_v^2.3.9/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-firestack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-firestack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-firestack/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-native-firestack/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-native-firestack/firestack.android' {
  declare module.exports: any;
}

declare module 'react-native-firestack/firestack.ios' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/firestack' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/firestackModule' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/analytics' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/authentication' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/base' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/cloudmessaging' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/database' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/presence' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/remoteConfig' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/modules/storage' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/utils/__tests__/log-test' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/utils/__tests__/promisify-test' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/utils/__tests__/singleton-test' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/utils/log' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/utils/promisify' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/utils/singleton' {
  declare module.exports: any;
}

declare module 'react-native-firestack/lib/utils/window-or-global' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-firestack/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-native-firestack/coverage/lcov-report/prettify'>;
}
declare module 'react-native-firestack/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-native-firestack/coverage/lcov-report/sorter'>;
}
declare module 'react-native-firestack/firestack.android.js' {
  declare module.exports: $Exports<'react-native-firestack/firestack.android'>;
}
declare module 'react-native-firestack/firestack.ios.js' {
  declare module.exports: $Exports<'react-native-firestack/firestack.ios'>;
}
declare module 'react-native-firestack/index' {
  declare module.exports: $Exports<'react-native-firestack'>;
}
declare module 'react-native-firestack/index.js' {
  declare module.exports: $Exports<'react-native-firestack'>;
}
declare module 'react-native-firestack/lib/firestack.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/firestack'>;
}
declare module 'react-native-firestack/lib/firestackModule.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/firestackModule'>;
}
declare module 'react-native-firestack/lib/modules/analytics.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/analytics'>;
}
declare module 'react-native-firestack/lib/modules/authentication.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/authentication'>;
}
declare module 'react-native-firestack/lib/modules/base.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/base'>;
}
declare module 'react-native-firestack/lib/modules/cloudmessaging.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/cloudmessaging'>;
}
declare module 'react-native-firestack/lib/modules/database.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/database'>;
}
declare module 'react-native-firestack/lib/modules/presence.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/presence'>;
}
declare module 'react-native-firestack/lib/modules/remoteConfig.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/remoteConfig'>;
}
declare module 'react-native-firestack/lib/modules/storage.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/modules/storage'>;
}
declare module 'react-native-firestack/lib/utils/__tests__/log-test.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/utils/__tests__/log-test'>;
}
declare module 'react-native-firestack/lib/utils/__tests__/promisify-test.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/utils/__tests__/promisify-test'>;
}
declare module 'react-native-firestack/lib/utils/__tests__/singleton-test.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/utils/__tests__/singleton-test'>;
}
declare module 'react-native-firestack/lib/utils/log.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/utils/log'>;
}
declare module 'react-native-firestack/lib/utils/promisify.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/utils/promisify'>;
}
declare module 'react-native-firestack/lib/utils/singleton.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/utils/singleton'>;
}
declare module 'react-native-firestack/lib/utils/window-or-global.js' {
  declare module.exports: $Exports<'react-native-firestack/lib/utils/window-or-global'>;
}
