// flow-typed signature: 1b5a08e94357dc1772dc1a364e37ac86
// flow-typed version: <<STUB>>/react-format-text_v^1.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-format-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-format-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-format-text/demo/index' {
  declare module.exports: any;
}

declare module 'react-format-text/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-format-text/demo/index.js' {
  declare module.exports: $Exports<'react-format-text/demo/index'>;
}
declare module 'react-format-text/dist/index.js' {
  declare module.exports: $Exports<'react-format-text/dist/index'>;
}
declare module 'react-format-text/index' {
  declare module.exports: $Exports<'react-format-text'>;
}
declare module 'react-format-text/index.js' {
  declare module.exports: $Exports<'react-format-text'>;
}
