// flow-typed signature: a0ebf8976491164df4b67efb567d6a9e
// flow-typed version: <<STUB>>/react-native-fit-image_v^1.3.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fit-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fit-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fit-image/dist/FitImage' {
  declare module.exports: any;
}

declare module 'react-native-fit-image/test/FitImage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fit-image/dist/FitImage.js' {
  declare module.exports: $Exports<'react-native-fit-image/dist/FitImage'>;
}
declare module 'react-native-fit-image/test/FitImage.js' {
  declare module.exports: $Exports<'react-native-fit-image/test/FitImage'>;
}
