// flow-typed signature: 0edfb2341348a161092786052ecd4f42
// flow-typed version: <<STUB>>/react-native-autolink_v^0.7.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-autolink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-autolink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-autolink/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-autolink/src/index.js' {
  declare module.exports: $Exports<'react-native-autolink/src/index'>;
}
