// flow-typed signature: 9b6d847a4d344f2b3a5fa2c25b3efcdb
// flow-typed version: <<STUB>>/react-native-collapsible_v^0.8.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-collapsible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-collapsible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-collapsible/Accordion' {
  declare module.exports: any;
}

declare module 'react-native-collapsible/Collapsible' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-collapsible/Accordion.js' {
  declare module.exports: $Exports<'react-native-collapsible/Accordion'>;
}
declare module 'react-native-collapsible/Collapsible.js' {
  declare module.exports: $Exports<'react-native-collapsible/Collapsible'>;
}
