// flow-typed signature: bb718ec275f16fe9867debe384a6ddcf
// flow-typed version: <<STUB>>/react-twitter-widgets_v^1.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-twitter-widgets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-twitter-widgets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-twitter-widgets/dist/components/AbstractWidget' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/dist/components/Follow' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/dist/components/Hashtag' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/dist/components/Mention' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/dist/components/Share' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/dist/components/Timeline' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/dist/components/Tweet' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/dist/index' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/site/src/App' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/site/src/App.test' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/site/src/index' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/site/src/WidgetExample' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/site/src/widgetPropExamples' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/components/AbstractWidget' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/components/Follow' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/components/Hashtag' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/components/Mention' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/components/Share' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/components/Timeline' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/components/Tweet' {
  declare module.exports: any;
}

declare module 'react-twitter-widgets/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-twitter-widgets/dist/components/AbstractWidget.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/components/AbstractWidget'>;
}
declare module 'react-twitter-widgets/dist/components/Follow.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/components/Follow'>;
}
declare module 'react-twitter-widgets/dist/components/Hashtag.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/components/Hashtag'>;
}
declare module 'react-twitter-widgets/dist/components/Mention.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/components/Mention'>;
}
declare module 'react-twitter-widgets/dist/components/Share.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/components/Share'>;
}
declare module 'react-twitter-widgets/dist/components/Timeline.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/components/Timeline'>;
}
declare module 'react-twitter-widgets/dist/components/Tweet.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/components/Tweet'>;
}
declare module 'react-twitter-widgets/dist/index.js' {
  declare module.exports: $Exports<'react-twitter-widgets/dist/index'>;
}
declare module 'react-twitter-widgets/site/src/App.js' {
  declare module.exports: $Exports<'react-twitter-widgets/site/src/App'>;
}
declare module 'react-twitter-widgets/site/src/App.test.js' {
  declare module.exports: $Exports<'react-twitter-widgets/site/src/App.test'>;
}
declare module 'react-twitter-widgets/site/src/index.js' {
  declare module.exports: $Exports<'react-twitter-widgets/site/src/index'>;
}
declare module 'react-twitter-widgets/site/src/WidgetExample.js' {
  declare module.exports: $Exports<'react-twitter-widgets/site/src/WidgetExample'>;
}
declare module 'react-twitter-widgets/site/src/widgetPropExamples.js' {
  declare module.exports: $Exports<'react-twitter-widgets/site/src/widgetPropExamples'>;
}
declare module 'react-twitter-widgets/src/components/AbstractWidget.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/components/AbstractWidget'>;
}
declare module 'react-twitter-widgets/src/components/Follow.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/components/Follow'>;
}
declare module 'react-twitter-widgets/src/components/Hashtag.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/components/Hashtag'>;
}
declare module 'react-twitter-widgets/src/components/Mention.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/components/Mention'>;
}
declare module 'react-twitter-widgets/src/components/Share.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/components/Share'>;
}
declare module 'react-twitter-widgets/src/components/Timeline.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/components/Timeline'>;
}
declare module 'react-twitter-widgets/src/components/Tweet.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/components/Tweet'>;
}
declare module 'react-twitter-widgets/src/index.js' {
  declare module.exports: $Exports<'react-twitter-widgets/src/index'>;
}
