// flow-typed signature: c07906b7a33a8bcd190866db97ee5503
// flow-typed version: <<STUB>>/react-native-back-android_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-back-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-back-android' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-back-android/src/index' {
  declare module.exports: any;
}

declare module 'react-native-back-android/src/press/hardwareBackPress' {
  declare module.exports: any;
}

declare module 'react-native-back-android/src/utils/exitApp' {
  declare module.exports: any;
}

declare module 'react-native-back-android/src/utils/isAndroid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-back-android/index' {
  declare module.exports: $Exports<'react-native-back-android'>;
}
declare module 'react-native-back-android/index.js' {
  declare module.exports: $Exports<'react-native-back-android'>;
}
declare module 'react-native-back-android/src/index.js' {
  declare module.exports: $Exports<'react-native-back-android/src/index'>;
}
declare module 'react-native-back-android/src/press/hardwareBackPress.js' {
  declare module.exports: $Exports<'react-native-back-android/src/press/hardwareBackPress'>;
}
declare module 'react-native-back-android/src/utils/exitApp.js' {
  declare module.exports: $Exports<'react-native-back-android/src/utils/exitApp'>;
}
declare module 'react-native-back-android/src/utils/isAndroid.js' {
  declare module.exports: $Exports<'react-native-back-android/src/utils/isAndroid'>;
}
