// flow-typed signature: b7f1b3d837d14062e7965e22d8702ae7
// flow-typed version: <<STUB>>/react-native-processinfo_v0.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-processinfo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-processinfo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-processinfo/index' {
  declare module.exports: $Exports<'react-native-processinfo'>;
}
declare module 'react-native-processinfo/index.js' {
  declare module.exports: $Exports<'react-native-processinfo'>;
}
