// flow-typed signature: e0437524278f01267618fd8efa211e87
// flow-typed version: <<STUB>>/stackdriver-errors-js_vgithub:mikelambert/stackdriver-errors-js/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stackdriver-errors-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stackdriver-errors-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stackdriver-errors-js/demo/demo-angular' {
  declare module.exports: any;
}

declare module 'stackdriver-errors-js/demo/demo' {
  declare module.exports: any;
}

declare module 'stackdriver-errors-js/demo/demo.min' {
  declare module.exports: any;
}

declare module 'stackdriver-errors-js/dist/stackdriver-errors-concat' {
  declare module.exports: any;
}

declare module 'stackdriver-errors-js/dist/stackdriver-errors-concat.min' {
  declare module.exports: any;
}

declare module 'stackdriver-errors-js/gulpfile' {
  declare module.exports: any;
}

declare module 'stackdriver-errors-js/stackdriver-errors' {
  declare module.exports: any;
}

declare module 'stackdriver-errors-js/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stackdriver-errors-js/demo/demo-angular.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/demo/demo-angular'>;
}
declare module 'stackdriver-errors-js/demo/demo.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/demo/demo'>;
}
declare module 'stackdriver-errors-js/demo/demo.min.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/demo/demo.min'>;
}
declare module 'stackdriver-errors-js/dist/stackdriver-errors-concat.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/dist/stackdriver-errors-concat'>;
}
declare module 'stackdriver-errors-js/dist/stackdriver-errors-concat.min.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/dist/stackdriver-errors-concat.min'>;
}
declare module 'stackdriver-errors-js/gulpfile.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/gulpfile'>;
}
declare module 'stackdriver-errors-js/stackdriver-errors.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/stackdriver-errors'>;
}
declare module 'stackdriver-errors-js/test/test.js' {
  declare module.exports: $Exports<'stackdriver-errors-js/test/test'>;
}
