// flow-typed signature: 7b982cd93cff682f3ba7247a357baeab
// flow-typed version: <<STUB>>/style-equal_v^1.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-equal/test/styleEqual-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-equal/index' {
  declare module.exports: $Exports<'style-equal'>;
}
declare module 'style-equal/index.js' {
  declare module.exports: $Exports<'style-equal'>;
}
declare module 'style-equal/test/styleEqual-test.js' {
  declare module.exports: $Exports<'style-equal/test/styleEqual-test'>;
}
