// flow-typed signature: fb17e8e832d3c8ea42ce3fab2ad907cc
// flow-typed version: <<STUB>>/uncss_vgiakki/uncss/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uncss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uncss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uncss/src/lib' {
  declare module.exports: any;
}

declare module 'uncss/src/phantom' {
  declare module.exports: any;
}

declare module 'uncss/src/uncss' {
  declare module.exports: any;
}

declare module 'uncss/src/utility' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uncss/src/lib.js' {
  declare module.exports: $Exports<'uncss/src/lib'>;
}
declare module 'uncss/src/phantom.js' {
  declare module.exports: $Exports<'uncss/src/phantom'>;
}
declare module 'uncss/src/uncss.js' {
  declare module.exports: $Exports<'uncss/src/uncss'>;
}
declare module 'uncss/src/utility.js' {
  declare module.exports: $Exports<'uncss/src/utility'>;
}
