// flow-typed signature: 96d4743f0cfa7be2b17990edb045831e
// flow-typed version: <<STUB>>/undefined_v^0.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'undefined'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'undefined' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'undefined/undefined' {
  declare module.exports: any;
}

// Filename aliases
declare module 'undefined/undefined.js' {
  declare module.exports: $Exports<'undefined/undefined'>;
}
