# DanceDeets App Engine Flexible Environment Configuration
# Default service

runtime: custom
env: flex
service: default

# Resource allocation
resources:
  memory_gb: 3.0
  cpu: 1
  disk_size_gb: 10

# Scaling configuration
manual_scaling:
  instances: 2

# Health checks - App Engine will check these endpoints
readiness_check:
  path: /_ah/health
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: /_ah/health
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2

# Network configuration
network:
  session_affinity: true

# Environment variables
env_variables:
  PYTHONUNBUFFERED: "1"

# Note: In Flexible environment, routing is handled by the application itself,
# not through handlers in app.yaml. The Flask/WSGI app handles all URL routing.
# Static files should be served by nginx or the application.
