source 'https://github.com/CocoaPods/Specs.git'

target 'DanceDeets' do
  pod 'Mixpanel'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/AdMob'
  #pod 'Google-Mobile-Ads-SDK', '~> 7.0'
end
