# -*-*- encoding: utf-8 -*-*-

import unittest

import scrapy

from classes.scraper.spiders import ny_expg

schedule_table = """<table id="classSchedule-mainTable" class="classSchedule-mainTable-loaded" cellspacing="0">
<thead><tr class="floatingHeaderRow" style="width: 930px;"><th id="startTimeHeader" class="floatingHeader" style="padding-left:10px;">Start time</th><th id="signUpNowHeader" class="floatingHeader" style="cursor:auto;">&nbsp;</th><th id="classNameHeader" valign="bottom" class="floatingHeader">Classes</th><th id="trainerNameHeader" valign="bottom" class="floatingHeader">Teacher</th><th id="resourceNameHeader" align="left" valign="bottom" class="floatingHeader">Room</th><th id="durationHeader" class="floatingHeader">Duration</th></tr> </thead><tbody><tr><td colspan="100%" class="header" id="an2"><b>&nbsp;<span class="headText">Mon&nbsp;</span>March 07, 2016&nbsp;</b></td></tr><tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;<s>4:00&nbsp;pm </s></td><td></td><td><s>Hip Hop(Intermediate)</s></td><td><span style="color:#990000;">Cancelled Today</span></td><td><s></s></td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>Hip Hop(Intermediate)</td><td>SORAYA LUNDY</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>Pop(Beginner)</td><td>PopNTod</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>DANCE HALL（All Levels）</td><td>Yaminah</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>Vogue(Intermediate)</td><td><span style="color:#990000;">Omari for Danielle Polanco</span> <span class="smallTextBlack"><a title="Regularly ScheduledDANIELLE POLANCO"><span style="color:#990000;">(1)</span></a></span></td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;<s>8:30&nbsp;pm </s></td><td></td><td><s>Lock(All Levels)</s></td><td><span style="color:#990000;">Cancelled Today</span></td><td><s></s></td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>Waack (Intermediate)</td><td>NUBIAN NENE</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;10:00&nbsp;pm </td><td></td><td>HOUSE MONDAYS &amp; Funk/Disco Session</td><td>EXPG Staff</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;55&nbsp;minutes</td></tr>
<tr><td colspan="100%" class="header" id="an3"><b>&nbsp;<span class="headText">Tue&nbsp;</span>March 08, 2016&nbsp;</b></td></tr><tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td></td><td>B-BOY FOOTWORKING (All Levels)</td><td>HEAT ROCK</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td></td><td>HOUSE(Beginner)</td><td>Mai Lé</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>Choreography Hiphop(Intermediate)</td><td><span style="color:#990000;">Supaman for Dr.EW</span> <span class="smallTextBlack"><a title="Regularly ScheduledDr.EW"><span style="color:#990000;">(2)</span></a></span></td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>Vogue(Intermediate)</td><td><span style="color:#990000;">Arturo Nugler for Danielle Polanco</span> <span class="smallTextBlack"><a title="Regularly ScheduledDANIELLE POLANCO"><span style="color:#990000;">(3)</span></a></span></td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>Hip Hop(Beginner)</td><td>TWEETBOOGIE</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>House(Intermediate)</td><td><span style="color:#990000;">Supaman for SEKOU</span> <span class="smallTextBlack"><a title="Regularly ScheduledSEKOU"><span style="color:#990000;">(4)</span></a></span></td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>B-Boy(All Levels)</td><td>VICTOR "KID GLYDE" ALICEA</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>Dance Class(Int/Adv)</td><td>CANDACE BROWN</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr><td colspan="100%" class="header" id="an4"><b>&nbsp;<span class="headText">Wed&nbsp;</span>March 09, 2016&nbsp;</b></td></tr><tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td></td><td>HOUSE(Absolute Beginner)</td><td>Huu Rock</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td></td><td>Waack (Beginner)</td><td>NUBIAN NENE</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>Dance Class(Int/Adv)</td><td>Eric Negron</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>LITE FEET(Beginner)</td><td>CHRYBABY COZIE</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>HOUSE(Beginner)</td><td>CEBO</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>Top Rock (All Levels)</td><td>SAMO</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>Hip Hop(Intermediate)</td><td><span style="color:#990000;">CEBO for BOBBY MILEAGE</span> <span class="smallTextBlack"><a title="Regularly ScheduledBOBBY MILEAGE"><span style="color:#990000;">(5)</span></a></span></td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>House (Intermediate)</td><td>TONE MCGREGOR</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;10:00&nbsp;pm </td><td></td><td><a href="javascript:;" name="cid82" class="modalClassDesc">Hiphop Wednesday</a></td><td>EXPG Staff</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;55&nbsp;minutes</td></tr>
<tr><td colspan="100%" class="header" id="an5"><b>&nbsp;<span class="headText">Thu&nbsp;</span>March 10, 2016&nbsp;</b></td></tr><tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td></td><td>Hip Hop(Beginner)</td><td>Stryke Force Ent.</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>Hip Hop(Intermediate)</td><td>SORAYA LUNDY</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>NEW STYLE HUSTLE (All Levels)</td><td>Jeff Selby</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>House(Intermediate)</td><td>JAMES "CRICKET" COLTER</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr><td colspan="100%" class="header" id="an6"><b>&nbsp;<span class="headText">Fri&nbsp;</span>March 11, 2016&nbsp;</b></td></tr><tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td></td><td>Hip Hop(Beginner)</td><td>Iron Bryan</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td></td><td>Waack (All Levles)</td><td>PRINCESS LOCKEROOO</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>Dance Class(Int/Adv)</td><td>Eric Negron</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td></td><td>POP (All Levels)</td><td>KATALYST</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td></td><td>House(Intermediate)</td><td>CEBO</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;<s>7:00&nbsp;pm </s></td><td></td><td><s>Lock (Int/Adv)</s></td><td><span style="color:#990000;">Cancelled Today</span></td><td><s></s></td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>Capoeira (All Levels)</td><td>Omi</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;8:30&nbsp;pm </td><td></td><td>NEW STYLE HUSTLE (All Levels)</td><td>Jeff Selby</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr><td colspan="100%" class="header" id="an7"><b>&nbsp;<span class="headText">Sat&nbsp;</span>March 12, 2016&nbsp;</b></td></tr><tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;2:30&nbsp;pm </td><td><input type="button" name="but466" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'Kid&amp;#39;s Hip Hop(5 - 7 years old) at 2:30 pm  on Saturday, 3/12/2016 with CEBO', '/ASP/res_a.asp?tg=22&amp;classId=466&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>Kid's Hip Hop(5 - 7 years old)</td><td>CEBO</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;2:30&nbsp;pm </td><td><input type="button" name="but1037" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'Kid&amp;#39;s Hip-Hop (8 - 10 Years Old) at 2:30 pm  on Saturday, 3/12/2016 with CHRYBABY COZIE', '/ASP/res_a.asp?tg=22&amp;classId=1037&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>Kid's Hip-Hop (8 - 10 Years Old)</td><td>CHRYBABY COZIE</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td><input type="button" name="but1038" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'HOUSE(Beginner/Intermediate) at 4:00 pm  on Saturday, 3/12/2016 with CEBO', '/ASP/res_a.asp?tg=22&amp;classId=1038&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>HOUSE(Beginner/Intermediate)</td><td>CEBO</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;4:00&nbsp;pm </td><td><input type="button" name="but897" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'VOGUE（All Levels） at 4:00 pm  on Saturday, 3/12/2016 with Leiomy', '/ASP/res_a.asp?tg=22&amp;classId=897&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>VOGUE（All Levels）</td><td>Leiomy </td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td><input type="button" name="but1041" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'DANCE CLASS (Intermediate) at 5:30 pm  on Saturday, 3/12/2016 with Dister', '/ASP/res_a.asp?tg=22&amp;classId=1041&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>DANCE CLASS (Intermediate)</td><td>Dister</td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;5:30&nbsp;pm </td><td><input type="button" name="but1039" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'LITE FEET(All Levels) at 5:30 pm  on Saturday, 3/12/2016 with KEENEN', '/ASP/res_a.asp?tg=22&amp;classId=1039&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>LITE FEET(All Levels)</td><td>KEENEN</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="evenRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td><input type="button" name="but437" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'FLEXIN(All levels) at 7:00 pm  on Saturday, 3/12/2016 with Regg Roc', '/ASP/res_a.asp?tg=22&amp;classId=437&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>FLEXIN(All levels)</td><td>Regg Roc</td><td>Studio B</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr class="oddRow"><td>&nbsp;&nbsp;&nbsp;7:00&nbsp;pm </td><td><input type="button" name="but1040" class="SignupButton" onclick="_gaq.push(['_trackEvent', 'Class_Schedule', 'click', 'Sign_Up_Now_button']);promptLogin('', 'HIPHOP (All Levels) at 7:00 pm  on Saturday, 3/12/2016 with Supaman for SPEX', '/ASP/res_a.asp?tg=22&amp;classId=1040&amp;classDate=3/12/2016&amp;clsLoc=1'); " value="Sign Up Now"></td><td>HIPHOP (All Levels)</td><td><span style="color:#990000;">Supaman for SPEX</span> <span class="smallTextBlack"><a title="Regularly ScheduledSPEX"><span style="color:#990000;">(6)</span></a></span></td><td>Studio A</td><td>&nbsp;1&nbsp;hour&nbsp;&amp;&nbsp;30&nbsp;minutes</td></tr>
<tr><td colspan="100%" class="header" id="an1"><b>&nbsp;<span class="headText">Sun&nbsp;</span>March 13, 2016&nbsp;</b></td></tr>
        <tr style="background-color:#F2F2F2;">
            <td class="" colspan="100%">&nbsp;&nbsp;&nbsp;&nbsp;no scheduled classes or training sessions</td>
        </tr>
<tr><td colspan="100%"><div class="foot-notes-container"><span class="headText bold">Regularly Scheduled:&nbsp;</span><span style="color:#990000;">(1)</span>&nbsp;DANIELLE POLANCO  <span style="color:#990000;">(2)</span>&nbsp;Dr.EW  <span style="color:#990000;">(3)</span>&nbsp;DANIELLE POLANCO  <span style="color:#990000;">(4)</span>&nbsp;SEKOU  <span style="color:#990000;">(5)</span>&nbsp;BOBBY MILEAGE  <span style="color:#990000;">(6)</span>&nbsp;SPEX  </div></td> </tr></tbody></table>
"""


class TestParse(unittest.TestCase):
    def runTest(self):
        spider = ny_expg.EXPG()
        selector = scrapy.Selector(text=schedule_table)
        items = list(spider.parse_classes(selector))
        self.assertEqual(items[0]['teacher'], 'Soraya Lundy')
